# #003_Pandas

In [23]:
import pandas as pd
import numpy as np

In [4]:
billboard = pd.read_csv('billboard.csv', engine = 'python')

In [20]:
billboard2 = billboard.melt(billboard.columns[:7]).set_index('year').loc[2000] #locë indexì ì´ë¦ì´ ê°ì ê²ì ë¤ ê°ì ¸ì¨ë¤.
billboard2

,artist.inverted,track,time,genre,date.entered,date.peaked,variable,value
year,,,,,,,,
2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,x1st.week,78.0
2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,x1st.week,15.0
2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,x1st.week,71.0
2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,x1st.week,41.0
2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,x1st.week,57.0
2000,Janet,Doesn't Really Matter,4:17,Rock,2000-06-17,2000-08-26,x1st.week,59.0
2000,Destiny's Child,Say My Name,4:31,Rock,1999-12-25,2000-03-18,x1st.week,83.0
2000,"Iglesias, Enrique",Be With You,3:36,Latin,2000-04-01,2000-06-24,x1st.week,63.0
2000,Sisqo,Incomplete,3:52,Rock,2000-06-24,2000-08-12,x1st.week,77.0
2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,x1st.week,81.0
2000,N'Sync,It's Gonna Be Me,3:10,Rock,2000-05-06,2000-07-29,x1st.week,82.0
2000,"Aguilera, Christina",What A Girl Wants,3:18,Rock,1999-11-27,2000-01-15,x1st.week,71.0
2000,Vertical Horizon,Everything You Want,4:01,Rock,2000-01-22,2000-07-15,x1st.week,70.0
2000,Creed,With Arms Wide Open,3:52,Rock,2000-05-13,2000-11-11,x1st.week,84.0
2000,Aaliyah,Try Again,4:03,Rock,2000-03-18,2000-06-17,x1st.week,59.0
2000,matchbox twenty,Bent,4:12,Rock,2000-04-29,2000-07-22,x1st.week,60.0
2000,"Carey, Mariah",Thank God I Found You,4:14,Rock,1999-12-11,2000-02-19,x1st.week,82.0
2000,"Hill, Faith",Breathe,4:04,Rap,1999-11-06,2000-04-22,x1st.week,81.0
2000,Mya,Case Of The Ex (Whatcha Gonna Do),3:50,Rock,2000-08-19,2000-12-02,x1st.week,72.0
2000,Dream,He Loves U Not,3:43,Rock,2000-09-30,2000-12-30,x1st.week,99.0
2000,"Braxton, Toni",He Wasn't Man Enough,4:21,Rock,2000-03-18,2000-05-06,x1st.week,63.0
2000,"Anthony, Marc",You Sang To Me,3:50,Latin,2000-02-26,2000-06-03,x1st.week,77.0
2000,98ï¿½,Give Me Just One Night (Una Noche),3:24,Rock,2000-08-19,2000-09-30,x1st.week,51.0
2000,Destiny's Child,Jumpin' Jumpin',3:48,Rock,2000-05-13,2000-08-19,x1st.week,74.0
2000,3 Doors Down,Kryptonite,3:53,Rock,2000-04-08,2000-11-11,x1st.week,81.0
2000,Sisqo,Thong Song,4:05,Rock,2000-01-29,2000-05-20,x1st.week,74.0
2000,"Aguilera, Christina",I Turn To You,4:00,Rock,2000-04-15,2000-07-01,x1st.week,50.0
2000,"Houston, Whitney",My Love Is Your Love,4:16,Rock,1999-09-04,2000-01-08,x1st.week,81.0
2000,Joe,I Wanna Know,4:57,Rock,2000-01-01,2000-07-01,x1st.week,94.0
2000,"Jordan, Montell",Get It On.. Tonite,4:34,Rap,1999-10-23,2000-02-12,x1st.week,92.0
...,...,...,...,...,...,...,...,...
2000,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,2000-09-02,2000-09-09,x76th.week,NaN
2000,Madison Avenue,Don't Call Me Baby,3:44,Electronica,2000-07-08,2000-09-16,x76th.week,NaN
2000,Eve,Got It All,3:48,Rap,2000-07-15,2000-07-22,x76th.week,NaN
2000,Limp Bizkit,Re-Arranged,4:08,Rock,1999-12-04,2000-02-05,x76th.week,NaN
2000,"Spencer, Tracie",Still In My Heart,4:11,Rock,2000-03-04,2000-03-11,x76th.week,NaN
2000,Nu Flavor,3 Little Words,3:54,R&B,2000-06-03,2000-06-17,x76th.week,NaN
2000,Tamar,If You Don't Wanna Love Me,4:02,Rock,2000-03-25,2000-04-15,x76th.week,NaN
2000,"Levert, Gerald",Baby U Are,4:10,R&B,2000-08-19,2000-08-26,x76th.week,NaN
2000,"Hart, Beth",L.A. Song,3:47,Country,1999-11-27,2000-01-15,x76th.week,NaN
2000,"Diffie, Joe",The Quittin' Kind,3:23,Country,2000-01-01,2000-01-22,x76th.week,NaN
2000,Funkmaster Flex,Do You,4:14,Rap,2000-11-11,2000-12-02,x76th.week,NaN
2000,"Price, Kelly",Love Sets You Free,3:46,Rock,2000-05-13,2000-05-20,x76th.week,NaN
2000,En Vogue,Riddle,5:10,Rock,2000-06-17,2000-06-17,x76th.week,NaN
2000,"Herndon, Ty",No Mercy,4:43,Country,2000-03-18,2000-05-06,x76th.week,NaN
2000,Anastacia,I'm Outta Love,4:01,Pop,2000-04-01,2000-04-01,x76th.week,NaN
2000,Trina,Pull Over,2:58,Rap,2000-09-09,2000-09-16,x76th.week,NaN
2000,Lil' Mo,Ta Da,4:17,Rap,2000-08-12,2000-09-16,x76th.week,NaN
2000,A*Teens,Dancing Queen,3:44,Pop,2000-07-08,2000-07-29,x76th.week,NaN
2000,"Sheist, Shade",Where I Wanna Be,4:16,Rap,2000-11-11,2000-11-18,x76th.week,NaN
2000,De La Soul,All Good?,5:02,Rap,2000-12-23,2000-12-23,x76th.week,NaN
2000,"Larrieux, Amel",Get Up,4:02,R&B,2000-03-04,2000-03-11,x76th.week,NaN
2000,"Braxton, Toni",Spanish Guitar,4:24,Rock,2000-12-02,2000-12-02,x76th.week,NaN
2000,Tuesday,I Know,4:06,Rock,2000-12-30,2000-12-30,x76th.week,NaN
2000,LL Cool J,Imagine That,4:00,Rap,2000-08-12,2000-08-19,x76th.week,NaN
2000,Master P,Souljas,3:33,Rap,2000-11-18,2000-11-18,x76th.week,NaN
2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,x76th.week,NaN
2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,x76th.week,NaN
2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,x76th.week,NaN
2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,x76th.week,NaN
2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,x76th.week,NaN

In [7]:
billboard.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 83 columns):
year               317 non-null int64
artist.inverted    317 non-null object
track              317 non-null object
time               317 non-null object
genre              317 non-null object
date.entered       317 non-null object
date.peaked        317 non-null object
x1st.week          317 non-null int64
x2nd.week          312 non-null float64
x3rd.week          307 non-null float64
x4th.week          300 non-null float64
x5th.week          292 non-null float64
x6th.week          280 non-null float64
x7th.week          269 non-null float64
x8th.week          260 non-null float64
x9th.week          253 non-null float64
x10th.week         244 non-null float64
x11th.week         236 non-null float64
x12th.week         222 non-null float64
x13th.week         210 non-null float64
x14th.week         204 non-null float64
x15th.week         197 non-null float64
x16th.week         182 non-null float64
x17th.week         177 non-null float64
x18th.week         166 non-null float64
x19th.week         156 non-null float64
x20th.week         146 non-null float64
x21st.week         65 non-null float64
x22nd.week         55 non-null float64
x23rd.week         48 non-null float64
x24th.week         46 non-null float64
x25th.week         38 non-null float64
x26th.week         36 non-null float64
x27th.week         29 non-null float64
x28th.week         24 non-null float64
x29th.week         20 non-null float64
x30th.week         20 non-null float64
x31st.week         19 non-null float64
x32nd.week         18 non-null float64
x33rd.week         12 non-null float64
x34th.week         10 non-null float64
x35th.week         9 non-null float64
x36th.week         9 non-null float64
x37th.week         9 non-null float64
x38th.week         8 non-null float64
x39th.week         8 non-null float64
x40th.week         7 non-null float64
x41st.week         7 non-null float64
x42nd.week         6 non-null float64
x43rd.week         6 non-null float64
x44th.week         6 non-null float64
x45th.week         5 non-null float64
x46th.week         5 non-null float64
x47th.week         5 non-null float64
x48th.week         4 non-null float64
x49th.week         4 non-null float64
x50th.week         4 non-null float64
x51st.week         4 non-null float64
x52nd.week         4 non-null float64
x53rd.week         4 non-null float64
x54th.week         2 non-null float64
x55th.week         2 non-null float64
x56th.week         2 non-null float64
x57th.week         2 non-null float64
x58th.week         2 non-null float64
x59th.week         2 non-null float64
x60th.week         2 non-null float64
x61st.week         2 non-null float64
x62nd.week         2 non-null float64
x63rd.week         2 non-null float64
x64th.week         2 non-null float64
x65th.week         1 non-null float64
x66th.week         0 non-null float64
x67th.week         0 non-null float64
x68th.week         0 non-null float64
x69th.week         0 non-null float64
x70th.week         0 non-null float64
x71st.week         0 non-null float64
x72nd.week         0 non-null float64
x73rd.week         0 non-null float64
x74th.week         0 non-null float64
x75th.week         0 non-null float64
x76th.week         0 non-null float64
dtypes: float64(75), int64(2), object(6)
memory usage: 205.6+ KB

In [11]:
billboard.columns[7:] #ì´ì ë½ìë¸ë¤, indexê° ëì¤ë ì´ì ë ë´ë¶ì ì¼ë¡ columnsë indexë¡ êµ¬íëìê¸° ëë¬¸.

Index(['x1st.week', 'x2nd.week', 'x3rd.week', 'x4th.week', 'x5th.week',
       'x6th.week', 'x7th.week', 'x8th.week', 'x9th.week', 'x10th.week',
       'x11th.week', 'x12th.week', 'x13th.week', 'x14th.week', 'x15th.week',
       'x16th.week', 'x17th.week', 'x18th.week', 'x19th.week', 'x20th.week',
       'x21st.week', 'x22nd.week', 'x23rd.week', 'x24th.week', 'x25th.week',
       'x26th.week', 'x27th.week', 'x28th.week', 'x29th.week', 'x30th.week',
       'x31st.week', 'x32nd.week', 'x33rd.week', 'x34th.week', 'x35th.week',
       'x36th.week', 'x37th.week', 'x38th.week', 'x39th.week', 'x40th.week',
       'x41st.week', 'x42nd.week', 'x43rd.week', 'x44th.week', 'x45th.week',
       'x46th.week', 'x47th.week', 'x48th.week', 'x49th.week', 'x50th.week',
       'x51st.week', 'x52nd.week', 'x53rd.week', 'x54th.week', 'x55th.week',
       'x56th.week', 'x57th.week', 'x58th.week', 'x59th.week', 'x60th.week',
       'x61st.week', 'x62nd.week', 'x63rd.week', 'x64th.week', 'x65th.week',
       'x66th.week', 'x67th.week', 'x68th.week', 'x69th.week', 'x70th.week',
       'x71st.week', 'x72nd.week', 'x73rd.week', 'x74th.week', 'x75th.week',
       'x76th.week'],
      dtype='object')

In [15]:
billboard.index #íì¼ë¡ ë½ëë¤. indexë rangeê¸°ë°ì¼ë¡ ë§ë¤ì´ì¡ë¤. ìíì¤ê¸° ëë¬¸ì indexingê³¼ slicing ê°ë¥

RangeIndex(start=0, stop=317, step=1)

---

In [21]:
a = {1,2,3}
b = {3,4}

In [22]:
a.intersection(b) #êµì§í© == a.intersection([3,4])

{3}

- pandasììë êµì§í©ì ì´ì©í´ ìíë indexë¥¼ ë½ì ì ìë¤.

---

In [25]:
a = np.arange(10)
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [26]:
a[a>3] #Trueë§ ë½ìì¤ë¤.

array([4, 5, 6, 7, 8, 9])

In [27]:
a[(a>3) & (a<9)]

array([4, 5, 6, 7, 8])

---

- ìë¡ì´ ì°ì°ì ë§ë¤ê¸° (ì°ì°ì ì¤ë²ë¡ë©)

In [28]:
class X(int):
    def __add__(self,other):
        print('ìëí´ì¤')

In [29]:
X(3) + X(5)

ìëí´ì¤

---

- isin : ì´ëì ë¬´ìì´ ìëê° ìëê°,

In [36]:
a = np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [41]:
a>2

array([False, False, False,  True,  True])

In [42]:
a[a>2]

array([3, 4])

---

### Where()

-

In [52]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.where(a>4,1,0) #ë¤ì ì¡°ê±´ì´ ë¶ì¼ë©´ ê°ì ë³ê²½ìí¬ ì ìë¤.

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [53]:
np.where(a==4) # numpyìë indexë²í¸ë¥¼ ë¶ë¬ì¬ ì ìê¸° ëë¬¸ì ì¬ì©ëë¤.

(array([4]),)

In [ ]:
billboard2.where() #ì¡°ê±´ì ë§ì¼ë©´ ë³íx, ì¡°ê±´ì´ ë§ì§ìì¼ë©´ ë³íO

---

In [54]:
import seaborn as sns

In [56]:
tips = sns.load_dataset('tips')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [60]:
tips['time2'] = tips.time.astype('object') #astype : ë°ì´í° íìì ë³ê²½í  ì ìë¤.ë¨, ë¬¸ìììë§ ì°ëë¡ íì.

In [62]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
total_bill    244 non-null float64
tip           244 non-null float64
sex           244 non-null category
smoker        244 non-null category
day           244 non-null category
time          244 non-null category
size          244 non-null int64
time2         244 non-null object
dtypes: category(4), float64(2), int64(1), object(1)
memory usage: 9.1+ KB

In [64]:
x = tips.time2.str #time2ê° ì¤ë¸ì í¸ì¼ëì íí´ì strì ì§ìíë¤.

In [70]:
x.count()

In [68]:
y = tips['time'].cat

In [69]:
y.categories # ì¹¼ë¼ì´ ì¹´íê³ ë¦¬ì¼ë catë¥¼ ì§ìíë¤.

Index(['Lunch', 'Dinner'], dtype='object')

In [73]:
tips = sns.load_dataset('tips')
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
total_bill    244 non-null float64
tip           244 non-null float64
sex           244 non-null category
smoker        244 non-null category
day           244 non-null category
time          244 non-null category
size          244 non-null int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.2 KB

In [74]:
tips.size = tips.size.astype('category') #ì´ë¯¸ sizeë¼ë ë´ì¥ ë©ìëê° ìë¤.

TypeError: data type "category" not understood

In [75]:
tips['size'] = tips['size'].astype('category')

In [76]:
tips.info() #ë¯¸ì±ë°ì´í°ê° ìëì§ íì¸

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
total_bill    244 non-null float64
tip           244 non-null float64
sex           244 non-null category
smoker        244 non-null category
day           244 non-null category
time          244 non-null category
size          244 non-null category
dtypes: category(5), float64(2)
memory usage: 5.8 KB

In [80]:
tips.describe().loc['mean':] # ì´ì  sizeë ì«ìê° ìë ë¬¸ìì´ì²ë¼ ì¸ìíë¤, numpyë í¸ëª¨ì§ëì´ì¤ëê¹ ë¤ floatë¡ ì²ë¦¬íë¤.
#ë°ì´í°ì íì§ì ìê¸°ìí´

      total_bill        tip
mean   19.785943   2.998279
std     8.902412   1.383638
min     3.070000   1.000000
25%    13.347500   2.000000
50%    17.795000   2.900000
75%    24.127500   3.562500
max    50.810000  10.000000